#!/bin/bash
# echo git branch for color PS1

name=`git symbolic-ref --short HEAD 2> /dev/null`
if [[ -z ${name} ]]
then
    exit
fi

st=`git status`

if [[ -n `echo ${st} | grep "nothing to commit"` ]]
then
    state=""
elif [[ -n `echo ${st} | grep "nothing added to commit but untracked files present"` ]]
then
    state="+ "
else
    state="* "
fi

if [[ -n `echo ${st} | grep "# Your branch is ahead of"` ]]
then
    remote=" ↑"
elif [[ -n `echo ${st} | grep "# Your branch is behind of"` ]]
then
    remote=" ↓"
elif [[ -n `echo ${st} | grep "# Your branch and (.*) have diverged"` ]]
then
    remote=" ↕"
fi

echo "[${state}${name}${remote}]"
